### ISSUE TITLE
xd对HOI4工具开发有兴趣吗? 

### ISSUE THREAD

**Issue by textGamex** [Supheria/warring_states#1]
还有兴趣的话可以看看我这个[项目](https://github.com/textGamex/Moder), 一个人做不过来()

**Comment by Supheria** [comment]
> 还有兴趣的话可以看看我这个[项目](https://github.com/textGamex/Moder), 一个人做不过来()

不好意思，我现在才注意到这里竟然有一个issue。有兴趣的，我这两天会看一下
